sudo: required
services:
  - docker
before_install:
  - docker build -t root/dockerworkflow -f Dockerfile.dev .

script:
  - docker run -e CI=true root/dockerworkflow npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-763865802519"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
        secure: $AWS_ACCESS_KEY
  secret_access_key:
        secure: $AWS_SECRET_KEY
